language: java

jdk:
- oraclejdk8
- oraclejdk7
- openjdk6

env:
- TERM=dumb

after_success:
- mvn clean cobertura:cobertura coveralls:report
- mvn clean test jacoco:report coveralls:report

sudo: false
